nome = input('Nome:')
print('Prazer em te conhecer {:>20}'.format(nome))
print('Prazer em te conhecer {:<20}'.format(nome))
print('Prazer em te conhecer {:^20}'.format(nome))
print('Prazer em te conhecer {:=>20}'.format(nome))
print('Prazer em te conhecer {:=<20}'.format(nome))
print('Prazer em te conhecer {:=^20}'.format(nome))