n = input('Digite algo: ')
print("Type: {}".format(type(n)))
print("Numereric: {}".format(n.isnumeric()))
print("Alpha: {}".format(n.isalpha()))
print("AlphaNum: {}".format(n.isalnum()))
print("Upper: {}".format(n.isupper()))
print("Lower: {}".format(n.islower()))
print("Printable: {}".format(n.isprintable()))
print("Digit: {}".format(n.isdigit()))
print("Title: {}".format(n.istitle()))
print("ASCII: {}".format(n.isascii()))
print("Decimal: {}".format(n.isdecimal()))
print("Identifier: {}".format(n.isidentifier()))
print("Space: {}".format(n.isspace()))