n = input('Digite algo: ')
print("Type: ", type(n))
print("Numereric: ", n.isnumeric())
print("Alpha: ", n.isalpha())
print("AlphaNum: ", n.isalnum())
print("Upper: ", n.isupper())
print("Lower: ", n.islower())
print("Printable: ", n.isprintable())
print("Digit: ", n.isdigit())
print("Title: ", n.istitle())
print("ASCII: ", n.isascii())
print("Decimal: ", n.isdecimal())
print("Identifier: ", n.isidentifier())
print("Space: ", n.isspace())